//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenLiquidacion
    {
        public int Id_Liquidacion { get; set; }
        public int Id_Empleado { get; set; }
        public Nullable<int> MontoIngreso { get; set; }
        public Nullable<int> MontoEgreso { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Liquidacion_Mensual Liquidacion_Mensual { get; set; }
    }
}
